### ISSUE TITLE
Methods to disconnect and reconnect dialup

### ISSUE THREAD

**Issue by alessandrocarrese** [Salamek/huawei-lte-api#103]
Are these methods available? 

Thanks

**Comment by Salamek** [comment]
@alessandrocarrese https://github.com/Salamek/huawei-lte-api/blob/master/huawei_lte_api/api/DialUp.py (?yeah?)

**Comment by alessandrocarrese** [comment]
yes, can I use _set_mobile_dataswitch_ to enable and disable the modem so I can get a new ip?

Thanks

**Comment by Salamek** [comment]
@alessandrocarrese well you have to try it your self, it will depend on your LTE internet provider since IP assignment is not something that client can easily affect without changing NIC MAC. Usually DHCP and alike provided IPs have some expiration/reservation time for what they are reserved for given NIC MAC and so on...

**Comment by alessandrocarrese** [comment]
yes, I am going to try,. Do you also know if this method works also for 3G or 4G?

**Comment by Salamek** [comment]
@alessandrocarrese it should work any "dialup" interface in supported Huawei devices
