### ISSUE TITLE
Quicksetup

### ISSUE THREAD

**Issue by 1fexd** [Salamek/huawei-lte-api#171]
Hi, is there any way to use this library for quicksetup my use case is as follows:

Sometimes the router's internet speed drops very low so I have to manually reset it in the settings panel everytime. I want to automate that. Resetting is possible using this library, but I haven't found a way through the quicksetup yet.

Kind regards

**Comment by Salamek** [comment]
What do you mean y `quicksetup`?

**Comment by 1fexd** [comment]
When you reset the router, it starts in quicksetup mode where you have to provide the default admin password (which is admin) and then setup the wifi.

**Comment by Salamek** [comment]
Maybe you want to restart your router instead of factory reset (`Device.set_control(ControlModeEnum.REBOOT)`)?

**Comment by 1fexd** [comment]
See, the problem is that for some reason, after a fews days/weeks of contious use, the download speed drops tremendously. This can only be fixed by resetting the router and re-configuring it (e.g. setting wifi name + pass and admin password). I wanted to create a small python script that does that for me, but as it turns out after resetting the router enters some kind of quicksetup mode where I can't set the admin password and wifi credentials.

**Comment by Salamek** [comment]
If that is what your router is doing, i would suggest returning it as broken and getting my $ back...
But if that is not a option for you, you are on your own in figuring out how that quicksetup works since i never encountered it my self... i guess it will use some already implemented API calls but IDK you need to check HTTP requests in web UI to see what it is calling and try to recreate it using this API...
