### ISSUE TITLE
Session related issue

### ISSUE THREAD

**Issue by tomasz8w** [Salamek/huawei-lte-api#65]
Hi,
I'm opening this issue as a continuation of reported problems with HomeAssistant huawei_lte integration that started few months ago. [https://github.com/home-assistant/home-assistant/issues/29901](url)
When trying to set up huawei_lte platform this error occurs:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 192, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/huawei_lte/__init__.py", line 288, in async_setup_entry
    connection = await hass.async_add_executor_job(get_connection)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/huawei_lte/__init__.py", line 277, in get_connection
    url, username=username, password=password, timeout=CONNECTION_TIMEOUT
  File "/usr/local/lib/python3.7/site-packages/huawei_lte_api/AuthorizedConnection.py", line 24, in __init__
    if self.user.login(True):
  File "/usr/local/lib/python3.7/site-packages/huawei_lte_api/api/User.py", line 76, in login
    state_login = self.state_login()
  File "/usr/local/lib/python3.7/site-packages/huawei_lte_api/api/User.py", line 27, in state_login
    return self._connection.get('user/state-login')
  File "/usr/local/lib/python3.7/site-packages/huawei_lte_api/Connection.py", line 22, in wrapped
    return fn(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/huawei_lte_api/Connection.py", line 166, in get
    timeout=self.timeout,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
As @scop suggested I did some test using script below:
```
#!/usr/bin/env python3

import http.client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
from huawei_lte_api.Connection import Connection
from huawei_lte_api.Client import Client

URL = "http://192.168.1.1/"
USERNAME = "admin"
PASSWORD = ""
CONNECTION_TIMEOUT = 10

http.client.HTTPConnection.debuglevel = 1

if USERNAME or PASSWORD:
    connection = AuthorizedConnection(
        URL, username=USERNAME, password=PASSWORD, timeout=CONNECTION_TIMEOUT
    )
else:
    connection = Connection(URL, timeout=CONNECTION_TIMEOUT)

if isinstance(connection, AuthorizedConnection):
    Client(connection).user.logout()
```
and what I found - all versions of huawei_lte_api after 1.2 and till 1.4.3 does not return any error. With 1.4.4 and newer, script throws error with credentials provided.

I'm using huawei b252s-23a.

**Comment by scop** [comment]
> I'm using huawei b252s-23a.

Hm, just to confirm: it's a b252s-23a, and not b525s-23a? I haven't
heard of the former, but I don't OTOH claim to have heard of every
model :)

**Comment by tomasz8w** [comment]
sorry, typo. it's b525s-23a of course ;)

**Comment by Salamek** [comment]
Hmm, looks like this is caused by https://github.com/Salamek/huawei-lte-api/commit/b1cba8281f2c42dbe2ac75e4dcbf4f70f0d6a696 ... maybe cookiejar was a bit slower than Session ? :smile:

@tomasz8w so B525S-23a huh? please check this issue https://github.com/Salamek/huawei-lte-api/issues/56 and let us know if that `time` hack mentioned in issue description works for you

**Comment by scop** [comment]
Shooting in the dark here, but the Django related requests issue talks about keep-alive implementation issue. If that's what this is about, maybe instead of adding arbitrary hacky sleeps, we we could try doing some of the initial requests that trigger this with keep-alive explicitly turned off, then continue with it on as usual instead?

**Comment by Salamek** [comment]
@scop i was looking into it and read same articles... there is no official way to disable keep-alive in latest python `requests` library... we may try to adding `Connection: close` to request header, or some other stuff... But without reliably reproducing this issue locally (meaning i need testing device again) trying this stuff and waiting for affected users to report if it works may be huge waste of time... 

What did https://github.com/Salamek/huawei-lte-api/commit/b1cba8281f2c42dbe2ac75e4dcbf4f70f0d6a696 fixed? Only better speed using keep-alive and cleaner code? If it is so, it seems like easiest and reliable solution to this issue is just revert https://github.com/Salamek/huawei-lte-api/commit/b1cba8281f2c42dbe2ac75e4dcbf4f70f0d6a696 but i would really hate to do that, using `requests.Session` is much cleaner solution...

PS:  i'm not trying to force PPL to use that `time` hack (i hate time hacks), i just want to narrow down if it is a same issue... and it probably is

**Comment by scop** [comment]
I believe in addition to the session benefits you mentioned I've witnessed fewer session related errors. There may have been some other ones, can't remember any more. But as said, it's really the right thing to do, and is also what practically every browser out there does, so... oh well.

I wouldn't revert that commit at least yet. If you want to have a try and go with disabling keep-alive for all requests but keep other session benefits until/if someone can come up with a more specific fix, this does the trick for me (verified with wireshark that it does actually close and grab new connections for every request):
```diff
index 0cd5f5b..06f5f77 100644
--- a/huawei_lte_api/Connection.py
+++ b/huawei_lte_api/Connection.py
@@ -39,4 +39,5 @@ class Connection:
     def __init__(self, url: str, timeout: Union[float, Tuple[float, float], None] = None):
         self.session = requests.Session()
+        self.session.headers["Connection"] = "close"
         self.url = url
         self.timeout = timeout
```
Might be good to make this configurable so that people who do not have the issues could continue with the keepalives.

Aside, users could almost do this themselves just by accessing connection's `session` attribute and do whatever they see fit with it, but unfortunately the `Connection` constructor goes and makes some requests before users can intercept. Something maybe to think about for the future.

On the other hand, if the above change is applied, users likely can _enable_ keep-alive again by accessing the `session` after the initial login/token stuff has been taken care of...

**Comment by Salamek** [comment]
ok lets try connection: close with boolean in Connection constructor to toggle... 

As you said, Connection is not mockable, and it will be rewritten when i will create unit tests...

@tomasz8w can you pls confirm that @scop patch fixes it for you ?

**Comment by tomasz8w** [comment]
I checked both, fix with sleep and @scop's fix but only the first one works for me.

**Comment by Salamek** [comment]
@scop ok, that did not work... what now? Until i get my hands on B525s-23a, i'm kinda out of ideas worth trying right now...

**Comment by blissarts** [comment]
Hi
In case it helps somehow: i have an B529s-23a and the same issue. 
BR

**Comment by scop** [comment]
Well, it's kind of good that it didn't work, means we don't have to give up on keepalive :)

Maybe try the delay, then. Something like this?
```diff
diff --git a/huawei_lte_api/api/User.py b/huawei_lte_api/api/User.py
index ea6c66f..e5cb054 100644
--- a/huawei_lte_api/api/User.py
+++ b/huawei_lte_api/api/User.py
@@ -1,6 +1,7 @@
 import base64
 import hashlib
 from typing import Optional
+from requests.exceptions import ConnectionError
 from huawei_lte_api.enums.user import PasswordTypeEnum, LoginStateEnum, LoginErrorEnum
 from huawei_lte_api.enums.client import ResponseEnum
 from huawei_lte_api.ApiGroup import ApiGroup
@@ -73,10 +74,18 @@ class User(ApiGroup):
         return result == ResponseEnum.OK.value
 
     def login(self, force_new_login: bool=False) -> bool:
-        try:
-            state_login = self.state_login()
-        except ResponseErrorNotSupportedException:
-            return True
+        retries = 4
+        for i in range(retries):
+            try:
+                state_login = self.state_login()
+            except ConnectionError:
+                # Some models reportedly close the connection if we attempt to access login state too
+                # soon after setting up the session etc. In that case, retry a couple of times.
+                if i == retries - 1:
+                    raise
+                time.sleep(i/5)
+            except ResponseErrorNotSupportedException:
+                return True
 
         if LoginStateEnum(int(state_login['State'])) == LoginStateEnum.LOGGED_IN and not force_new_login:
             return True
```
(If that works, we may want to be more targeted than just ConnectionError, i.e. try also looking up if its cause is RemoteDisconnected etc, but this shoud suffice for trying stuff out.)

I just occurred to me that library users could probably circumvent the issue already by setting `login_on_demand=True` perhaps delaying some before the login. But it should be handled by the lib transparently.

**Comment by tomasz8w** [comment]
Ok - looks that only 2 retries are enough to make it work and also no need to sleep. Catched error is 
```
('Connection aborted.', Remote disconnected('Remote end closed connection without response'))
```

**Comment by scop** [comment]
My guess is that it does just require "some time", which may be system/setup dependent, and retrying without sleeping ends up consuming a bit of time as a side effect. Retrying in a busy loop without any sleep whatsoever doesn't sound like a good idea to me. Anyway, will file a PR.

**Comment by scop** [comment]
#68 filed, final testing would be nice.

**Comment by tomasz8w** [comment]
I changed User.py according to #68  and tested it with the script but it's not working with second if condition:
```
or not isinstance(
                        getattr(e, '__context__', getattr(e, '__cause__', None)), ConnectionResetError):
```
but I'm not sure what is this part of code supposed to do so maybe it's alright?

**Comment by scop** [comment]
Thanks for testing. Comments about #68 would be better placed in #68 rather than here. I'll reply there.
